site_name: Advanced Computer Networking
# site_url: https://www.ustc.edu.cn
repo_name: snowzjx/COMP6103P
repo_url: https://github.com/snowzjx/COMP6103P
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true